
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassist-deployment
  labels:
    app: homeassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassist
  template:
    metadata:
      labels:
        app: homeassist
    spec:
      containers:
        - name: homeassist
          image: homeassistant/home-assistant
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: "/config"
              name: homeassist-persistent-storage
            - mountPath: /config/configuration.yaml
              subPath: configuration.yaml
              name: homeassist-config
      volumes:
        - name: homeassist-config
          configMap:
            name: homeassistant.config
            items:
            - key: configuration.yaml
              path: configuration.yaml
        - name: homeassist-persistent-storage
          nfs:
            server: qnap.kainz.local
            path: /kubestorage/homeassistant
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: homeassist
spec:
  type: ClusterIP
  selector:
    app: homeassist
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8123